Repository scienceandcode/habits-todo-backend, pull requests merged in 2024-12, with the labels that each got.

#1 Adiciona actions de deploy
  .github/workflows/production.yml
Labels: ci

#2 Corrige variável de ambente da pipeline de produção
  .github/workflows/production.yml
Labels: fix, ci

#3 Setup database local com docker compose
  .docker/config/postgres/Dockerfile
  .env.example
  .gitignore
  Makefile
  docker-compose.yml
Labels: feature

#4 doc: defines how to setup, dependencies and how to install the project
  README.md
Labels: documentation

#7 Created db package to handle database with gorm
  .env.example
  cmd/habits-todo-backend/main.go
  go.mod
  go.sum
  internal/db/db.go
  internal/repository/base_repository.go
  internal/repository/base_repository_test.go
Labels: feature
