Repository scienceandcode/habits-todo-backend, pull requests merged in 2025-03, with the labels that each got.

#24 Proteção de migrate via usuário administrador
  .env.example
  cmd/habits-todo-backend/main.go
  internal/api/controller/admin_controller.go
  internal/api/functions.go
  internal/api/middleware/admin_user_middleware.go
  internal/api/route/admin_routes.go
  internal/db/db.go
  internal/db/migrate.go
  internal/db/seeder.go
  internal/model/user.go
  internal/server/di/wire.go
  internal/server/di/wire_gen.go
  internal/server/server.go
  pkg/environment/environment.go
Labels: feature, improvement

#27 Adiciona Mailhog e pgAdmin no docker compose
  .env.example
  Makefile
  docker-compose.yml
Labels: dependencies

#25 Estrutura I18n base e piloto em rota Admin migrate models
  .env.example
  cmd/habits-todo-backend/main.go
  go.mod
  go.sum
  internal/api/controller/admin_controller.go
  internal/i18n/i18n.go
  internal/i18n/messages/en_us.go
  internal/i18n/messages/pt_br.go
  internal/i18n/supported_languages.go
Labels: feature

#26 Configura GOPATH no make setup
  Makefile
  README.md
Labels: improvement
